# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatereview', '0005_auto_20160323_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='document_relevance',
            field=models.CharField(default=b'False', max_length=10),
        ),
    ]
