# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatereview', '0006_auto_20160325_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='document_judged',
            new_name='documents_judged',
        ),
        migrations.AddField(
            model_name='review',
            name='pool',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paper',
            name='abstract_relevance',
            field=models.CharField(default=b'False', max_length=6),
        ),
        migrations.AlterField(
            model_name='paper',
            name='authors',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='paper',
            name='document_relevance',
            field=models.CharField(default=b'False', max_length=6),
        ),
        migrations.AlterField(
            model_name='review',
            name='query_string',
            field=models.CharField(default=b'', max_length=700),
        ),
    ]
